[package]
name = "odx_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bv = "0.11.1"
roxmltree = "0.16.0"
bitvec = "1"
lazy_static = "1.1.0"
marcolib = { path = "../marcolib" }